[package]
name = "euler58"
version = "0.1.0"
authors = ["russell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euler_lib = { path = "../euler_lib" }
